#! /usr/bin/env bash

set -eu

ROOTDIR=$(cd "$(dirname "$0")/.." && pwd)
cd "${ROOTDIR}"

usage() {
    echo "Usage:"
    echo "  scgen <servername> <serveraddr> <serverfake>"
    echo
    echo "This script generates <servername>.server files in "
    echo "${ROOTDIR}/private/servers directory"
    echo
    echo "<servername> should be arbitrary name for the server"
    echo "<serveraddr> should be the actual address (or dns) of the server"
    echo "<serverfake> should be the actual address (or dns) of the fake"
    echo "(vless) server"
}

echoerr() {
    echo "$@" 1>&2;
}

if [[ $# -ne 3 ]]; then
    usage
    exit 1
fi

SERVERNAME=$1
SERVERADDR=$2
SERVERFAKE=$3

SERVERENV="${ROOTDIR}/private/servers/${SERVERNAME}.server"

if [[ -f "${SERVERENV}" ]]; then
    echoerr ".server file for this server already exists"
    exit 1
fi

KEYPAIR=$(sing-box generate reality-keypair | cut --delimiter=" " --field=2)
PRIVATE_KEY=$(echo ${KEYPAIR} | cut -d " "  -f 1)
PUBLIC_KEY=$(echo ${KEYPAIR} | cut -d " " -f 2)

echo "SERVERADDR=\"${SERVERADDR}\"" > "${SERVERENV}"
echo "SERVERFAKE=\"${SERVERFAKE}\"" > "${SERVERENV}"
echo "PRIVATE_KEY=\"${PRIVATE_KEY}\"" > "${SERVERENV}"
echo "PUBLIC_KEY=\"${PUBLIC_KEY}\"" > "${SERVERENV}"
