#! /usr/bin/env bash

set -eu

ROOTDIR=$(cd "$(dirname "$0")/.." && pwd)
cd "${ROOTDIR}"

usage() {
    echo "Usage:"
    echo "  ucgen <username> <servername>"
    echo
    echo "This script will search in ${ROOTDIR}/private/users for files"
    echo "<username>.user and in ${ROOTDIR}/private/servers for files"
    echo "<servername>.server, which should be just env files for the shell"
    echo
    echo ".server files should contain variables SERVER, SERVER_NAME, PUBLIC_KEY, PRIVATE_KEY"
    echo ".user files should contain variables UUID and SHORT_ID"
}

echoerr() {
    echo "$@" 1>&2;
}

if [[ $# -ne 2 ]]; then
    usage
    exit 1
fi

USERNAME=$1
SERVERNAME=$2
USERENV="${ROOTDIR}/private/users/${USERNAME}.user"
SERVERENV="${ROOTDIR}/private/servers/${SERVERNAME}.server"

if [[ ! -f "${SERVERENV}" ]]; then
    echoerr "Generate .server file first"
    exit 1
fi

if [[ ! -f "${USERENV}" ]]; then
    UUID=$(sing-box generate uuid)
    SHORT_ID=$(sing-box generate rand 8 --hex)
    echo "UUID=\"${UUID}\"" > "${USERENV}"
    echo "SHORT_ID=\"${SHORT_ID}\"" >> "${USERENV}"
fi

source "${SERVERENV}"
source "${USERENV}"

CONFIG="private/configs/${USERNAME}.json"
CONFIG_ALL="private/configs/${USERNAME}-all.json"
cp config/template-client.json ${CONFIG}
cp config/template-all.json ${CONFIG_ALL}

sed -e "s/\"server\": \"\"/\"server\": \"${SERVERADDR}\"/g" \
-e "s/\"server_name\": \"\"/\"server_name\": \"${SERVERFAKE}\"/g" \
-e "s/\"public_key\": \"\"/\"public_key\": \"${PUBLIC_KEY}\"/g" \
-e "s/\"uuid\": \"\"/\"uuid\": \"${UUID}\"/g" \
-e "s/\"short_id\": \"\"/\"short_id\": \"${SHORT_ID}\"/g" \
${CONFIG} > ${CONFIG}.sed
mv ${CONFIG}.sed ${CONFIG}

sed -e "s/\"server\": \"\"/\"server\": \"${SERVERADDR}\"/g" \
-e "s/\"domain\": \"\"/\"domain\": \"${SERVERADDR}\"/g" \
-e "s/\"server_name\": \"\"/\"server_name\": \"${SERVERFAKE}\"/g" \
-e "s/\"public_key\": \"\"/\"public_key\": \"${PUBLIC_KEY}\"/g" \
-e "s/\"uuid\": \"\"/\"uuid\": \"${UUID}\"/g" \
-e "s/\"short_id\": \"\"/\"short_id\": \"${SHORT_ID}\"/g" \
${CONFIG_ALL} > ${CONFIG_ALL}.sed
mv ${CONFIG_ALL}.sed ${CONFIG_ALL}
